"use strict";
/**
 * Sprint 4 — LiveMemoryIntegration Integration Tests
 *
 * Covers (single-process categories of the Sprint 4 test matrix):
 *   • degraded init + kill-switch no-op safety
 *   • snapshot integrity validation (valid / tampered / missing history)
 *   • corruption walk-back (invalid newest snapshot is skipped, never deleted)
 *   • startup recovery report (domains, intents, memory summary, timing)
 *   • duplicate-startup protection (in-process second instance)
 *   • idempotent writes (trade open/close, restart, recovery, shutdown)
 *   • memory quarantine during recovery (structural corruption)
 *   • drift detection vs replay-built live state (observe-only)
 *   • large history (2 000 bulk events) recovery timing
 *   • restart + redeploy simulation (shutdown → new boot recovers from
 *     the shutdown snapshot, walking back over a newer corrupt snapshot)
 *
 * Two-OS-process scenarios (concurrent recovery, power loss/SIGKILL) live in
 * telemetry/tests/stress/mi_process.test.js.
 *
 * All test data uses source LIKE 'test_mi%' and is cleaned up. Snapshots
 * created during the run are removed by id-watermark in after().
 *
 * Run:
 *   node --test --test-reporter=spec telemetry/tests/integration/mi_integration.test.js
 */

const { describe, it, before, after } = require("node:test");
const assert = require("node:assert/strict");
const { Pool } = require("pg");

const { LiveMemoryIntegration } = require("../../managers");

const DATABASE_URL = process.env.DATABASE_URL || "";
let pool;               // raw SQL for fixtures + assertions
let snapWatermark = 0;  // system_snapshots.id watermark for cleanup
let testStart;
let fakeSnapshotId = null;

async function cleanupEvents(p) {
  await p.query(
    `DELETE FROM memory_event_history WHERE memory_id IN
       (SELECT id FROM memory_events WHERE source LIKE 'test_mi%')`
  );
  await p.query(`DELETE FROM memory_events WHERE source LIKE 'test_mi%'`);
}

before(async () => {
  assert.ok(DATABASE_URL, "DATABASE_URL must be set");
  pool = new Pool({ connectionString: DATABASE_URL, max: 5 });
  testStart = new Date();
  const { rows } = await pool.query(`SELECT COALESCE(MAX(id), 0) AS m FROM system_snapshots`);
  snapWatermark = Number(rows[0].m);
  await cleanupEvents(pool);
});

after(async () => {
  await cleanupEvents(pool);
  // Remove snapshots (and their history rows) created by this run only.
  await pool.query(
    `DELETE FROM runtime_domain_history WHERE snapshot_id IN
       (SELECT id FROM system_snapshots WHERE id > $1)`, [snapWatermark]
  );
  await pool.query(`DELETE FROM system_snapshots WHERE id > $1`, [snapWatermark]);
  // Remove consistency entries generated by this run.
  await pool.query(
    `DELETE FROM consistency_log
     WHERE detected_at >= $1
       AND (check_id LIKE 'recovery:%' OR check_id LIKE 'memory_validate:%')`,
    [testStart]
  );
  await pool.end();
});

// ── 1. Kill switch + degraded init ───────────────────────────────────────────

describe("MI — kill switch and degraded init", () => {

  it("enabled:false → init refuses, every method is a safe no-op", async () => {
    const lmi = new LiveMemoryIntegration({ enabled: false });
    const ini = await lmi.init();
    assert.equal(ini.ok, false);
    assert.equal(lmi.isActive, false);

    const rep = await lmi.recoverOnStartup();
    assert.equal(rep.recovered, false);
    assert.equal(rep.reason, "disabled");

    const rec = await lmi.recordTradeOpen({ symbol: "EUR_USD", side: "BUY" });
    assert.equal(rec.ok, false);

    assert.equal(lmi.startPeriodicPersistence(1000), false);

    const sd = await lmi.gracefulShutdown();
    assert.equal(sd.ok, false); // never initialized — nothing to flush
  });

  it("bad connection string → init degrades to no-op instead of throwing", async () => {
    const lmi = new LiveMemoryIntegration({ connectionString: "bogus://not-a-db" });
    const ini = await lmi.init();
    assert.equal(ini.ok, false);
    assert.match(ini.error, /postgres/);
    assert.equal(lmi.isActive, false);
    const rep = await lmi.recoverOnStartup();
    assert.equal(rep.recovered, false);
  });
});

// ── 2. Snapshot integrity validation ─────────────────────────────────────────

describe("MI — snapshot integrity validation", () => {
  let helper; // init'd but never takes the recovery lock

  before(async () => {
    helper = new LiveMemoryIntegration({ calledBy: "test_mi_helper" });
    const ini = await helper.init();
    assert.equal(ini.ok, true);
  });

  after(async () => {
    // helper never acquired the lock; shutdown just closes its pool
    await helper.gracefulShutdown({ reason: "helper-done" });
  });

  it("a freshly-taken snapshot passes validation", async () => {
    const { snapshotId } = await helper.rdm.takeSnapshot("manual", { calledBy: "test_mi_helper" });
    const snap = await helper.rdm.getSnapshot(snapshotId);
    const v = await helper.validateSnapshot(snap);
    assert.equal(v.valid, true, JSON.stringify(v.problems));
  });

  it("tampered checksum → invalid with a checksum problem", async () => {
    const { snapshotId } = await helper.rdm.takeSnapshot("manual", { calledBy: "test_mi_helper" });
    const snap = await helper.rdm.getSnapshot(snapshotId);
    const domains = Object.keys(snap.runtime_summary);
    snap.runtime_summary[domains[0]].checksum = "0".repeat(32);
    const v = await helper.validateSnapshot(snap);
    assert.equal(v.valid, false);
    assert.ok(v.problems.some(p => p.includes("checksum mismatch")));
  });

  it("snapshot with no history rows → invalid (missing history)", async () => {
    const { rows } = await pool.query(
      `INSERT INTO system_snapshots (trigger_type, runtime_summary, memory_summary, knowledge_summary, system_status)
       VALUES ('test_mi_fake', '{"live":{"version":1,"checksum":"deadbeef"}}'::jsonb, '{}'::jsonb, '{}'::jsonb, 'OPERATIONAL')
       RETURNING id`
    );
    const snap = await helper.rdm.getSnapshot(rows[0].id);
    const v = await helper.validateSnapshot(snap);
    assert.equal(v.valid, false);
    assert.ok(v.problems.some(p => p.includes("no history row")));
    await pool.query(`DELETE FROM system_snapshots WHERE id = $1`, [rows[0].id]);
  });

  it("malformed runtime_summary → invalid", async () => {
    const v = await helper.validateSnapshot({ id: 999999, runtime_summary: [1, 2, 3] });
    assert.equal(v.valid, false);
  });
});

// ── 3. Recovery lifecycle on one boot ────────────────────────────────────────

describe("MI — startup recovery lifecycle", () => {
  let A; // the "live process" instance — holds the lock through this block
  let firstReport;

  before(async () => {
    A = new LiveMemoryIntegration({ calledBy: "test_mi_int" });
    const ini = await A.init();
    assert.equal(ini.ok, true);
  });

  it("recoverOnStartup: full report, lock acquired, post-recovery snapshot", async () => {
    firstReport = await A.recoverOnStartup({ liveState: { dailyTrades: 0, openTrades: {} } });
    assert.equal(firstReport.recovered, true, firstReport.reason);
    assert.equal(firstReport.lockAcquired, true);
    assert.ok(Object.keys(firstReport.domains).length >= 1, "recovers runtime domains");
    assert.ok(firstReport.domains.live, "live domain recovered");
    assert.ok(Number.isFinite(firstReport.memoryTotal));
    assert.ok(firstReport.postRecoverySnapshotId > 0, "post_recovery snapshot taken");

    // SYSTEM_RECOVERY event written with per-boot dedupe key
    const { rows } = await pool.query(
      `SELECT * FROM memory_events WHERE dedupe_key = $1`,
      [`system_recovery:${firstReport.bootId}`]
    );
    assert.equal(rows.length, 1);
    assert.equal(rows[0].event_type, "SYSTEM_RECOVERY");
  });

  it("recovery timing: completes in under 10s", () => {
    assert.ok(firstReport.durationMs < 10000, `took ${firstReport.durationMs}ms`);
  });

  it("second recovery on the same boot is idempotent (recovery event deduped)", async () => {
    const before = A.getStatus().counters.eventsDeduped;
    const rep2 = await A.recoverOnStartup({ liveState: { dailyTrades: 0, openTrades: {} } });
    assert.equal(rep2.recovered, true);
    assert.ok(A.getStatus().counters.eventsDeduped > before, "SYSTEM_RECOVERY deduped");
    const { rows } = await pool.query(
      `SELECT COUNT(*) AS n FROM memory_events WHERE dedupe_key = $1`,
      [`system_recovery:${firstReport.bootId}`]
    );
    assert.equal(Number(rows[0].n), 1, "still exactly one recovery event for this boot");
  });

  it("duplicate startup (in-process second instance) degrades to observe-only", async () => {
    const B = new LiveMemoryIntegration({ calledBy: "test_mi_dup" });
    const ini = await B.init();
    assert.equal(ini.ok, true);
    const rep = await B.recoverOnStartup({ liveState: { dailyTrades: 0, openTrades: {} } });
    assert.equal(rep.recovered, false);
    assert.equal(rep.lockAcquired, false);
    assert.match(rep.reason, /lock/);
    // duplicate startup is logged, not fatal
    const { rows } = await pool.query(
      `SELECT COUNT(*) AS n FROM consistency_log
       WHERE check_id = 'recovery:duplicate_startup' AND detected_at >= $1`, [testStart]
    );
    assert.ok(Number(rows[0].n) >= 1);
    await B.gracefulShutdown({ reason: "dup-test-done" });
  });

  it("trade open/close hooks are idempotent within a minute bucket", async () => {
    const r1 = await A.recordTradeOpen({ symbol: "MI_EURUSD", side: "BUY" });
    const r2 = await A.recordTradeOpen({ symbol: "MI_EURUSD", side: "BUY" });
    assert.equal(r1.ok, true);
    assert.equal(r2.ok, true);
    const { rows: opens } = await pool.query(
      `SELECT COUNT(*) AS n FROM memory_events WHERE event_type = 'TRADE_OPENED' AND symbol = 'MI_EURUSD'`
    );
    assert.equal(Number(opens[0].n), 1, "duplicate open deduped");

    await A.recordTradeClose({ symbol: "MI_EURUSD", reason: "TP", profit: "2.5", breakEven: "true" });
    await A.recordTradeClose({ symbol: "MI_EURUSD", reason: "TP", profit: "2.5", breakEven: "true" });
    const { rows: closes } = await pool.query(
      `SELECT * FROM memory_events WHERE event_type = 'TRADE_CLOSED' AND symbol = 'MI_EURUSD'`
    );
    assert.equal(closes.length, 1, "duplicate close deduped");
    assert.equal(closes[0].payload.profit, 2.5, "profit coerced to number");
    assert.equal(closes[0].payload.breakEven, true, "breakEven coerced to boolean");
  });

  it("bot restart hook is idempotent per boot + restart count", async () => {
    await A.recordBotRestart({ exitCode: 1, restartCount: 7, delayMs: 5000 });
    await A.recordBotRestart({ exitCode: 1, restartCount: 7, delayMs: 5000 });
    const { rows } = await pool.query(
      `SELECT COUNT(*) AS n FROM memory_events
       WHERE event_type = 'BOT_RESTART' AND dedupe_key = $1`,
      [`bot_restart:${A.getStatus().bootId}:7`]
    );
    assert.equal(Number(rows[0].n), 1);
  });

  it("drift between replay-built live state and v2 live domain is detected and logged", async () => {
    const rep = await A.recoverOnStartup({
      liveState: { dailyTrades: 0, openTrades: { MI_PHANTOM: { symbol: "MI_PHANTOM" } } },
    });
    assert.equal(rep.recovered, true);
    assert.equal(rep.drift.hasDrift, true);
    assert.ok(rep.drift.fields.some(f => f.field === "openTrades"));
    const { rows } = await pool.query(
      `SELECT COUNT(*) AS n FROM consistency_log
       WHERE check_id = 'recovery:live_drift' AND detected_at >= $1`, [testStart]
    );
    assert.ok(Number(rows[0].n) >= 1, "drift logged to consistency_log");
  });

  it("structurally corrupt memory is quarantined (never deleted) during recovery", async () => {
    const { rows } = await pool.query(
      `INSERT INTO memory_events (event_type, runtime_domain, payload, source)
       VALUES ('TEST_MI_CORRUPT', 'live', '[]'::jsonb, 'test_mi_corrupt') RETURNING id`
    );
    const corruptId = rows[0].id;
    const rep = await A.recoverOnStartup({ liveState: { dailyTrades: 0, openTrades: {} } });
    assert.equal(rep.recovered, true);
    assert.ok(rep.quarantined >= 1, `expected quarantine, got ${rep.quarantined}`);
    const { rows: after } = await pool.query(`SELECT status FROM memory_events WHERE id = $1`, [corruptId]);
    assert.equal(after.length, 1, "corrupt row still exists — quarantined, not deleted");
    assert.equal(after[0].status, "CORRUPTED");
    // remove fixture so later recoveries in this run stay clean
    await pool.query(`DELETE FROM memory_event_history WHERE memory_id = $1`, [corruptId]);
    await pool.query(`DELETE FROM memory_events WHERE id = $1`, [corruptId]);
  });

  it("large history: recovery stays fast with 2 000 extra memories", async () => {
    await pool.query(`
      WITH ins AS (
        INSERT INTO memory_events (event_type, runtime_domain, payload, metadata, source)
        SELECT 'TEST_MI_BULK', 'live', '{}'::jsonb, '{}'::jsonb, 'test_mi_bulk'
        FROM generate_series(1, 2000)
        RETURNING id
      )
      INSERT INTO memory_event_history (memory_id, change_op, version, snapshot, changed_by)
      SELECT id, 'CREATE', 1, '{}'::jsonb, 'test_mi_bulk' FROM ins
    `);
    const rep = await A.recoverOnStartup({ liveState: { dailyTrades: 0, openTrades: {} } });
    assert.equal(rep.recovered, true);
    assert.ok(rep.memoryTotal >= 2000, `memoryTotal=${rep.memoryTotal}`);
    assert.ok(rep.durationMs < 15000, `large-history recovery took ${rep.durationMs}ms`);
  });

  it("corrupt newest snapshot: walk-back skips it (and never deletes it)", async () => {
    // Plant a corrupt snapshot that sorts NEWEST
    const { rows } = await pool.query(
      `INSERT INTO system_snapshots (created_at, trigger_type, runtime_summary, memory_summary, knowledge_summary, system_status)
       VALUES (NOW() + INTERVAL '1 minute', 'test_mi_fake',
               '{"live":{"version":999,"checksum":"ffffffffffffffffffffffffffffffff"}}'::jsonb,
               '{}'::jsonb, '{}'::jsonb, 'OPERATIONAL')
       RETURNING id`
    );
    fakeSnapshotId = Number(rows[0].id);

    const { snapshot, skipped } = await A.findLatestValidSnapshot();
    assert.ok(snapshot, "an older valid snapshot is found");
    assert.notEqual(Number(snapshot.id), fakeSnapshotId);
    assert.ok(skipped.some(s => s.id === fakeSnapshotId), "corrupt snapshot skipped");

    const { rows: still } = await pool.query(`SELECT id FROM system_snapshots WHERE id = $1`, [fakeSnapshotId]);
    assert.equal(still.length, 1, "corrupt snapshot NEVER deleted (sacred constraint)");

    const { rows: logged } = await pool.query(
      `SELECT COUNT(*) AS n FROM consistency_log
       WHERE check_id = 'recovery:snapshot_invalid' AND detected_at >= $1`, [testStart]
    );
    assert.ok(Number(logged[0].n) >= 1, "skip logged to consistency_log");
  });

  it("graceful shutdown: flushes in-flight writes, final event + snapshot, releases lock", async () => {
    // fire an un-awaited write right before shutdown — flush must land it
    A.recordTradeOpen({ symbol: "MI_FLUSH", side: "SELL" });
    const sd = await A.gracefulShutdown({ reason: "test-shutdown" });
    assert.equal(sd.ok, true);
    assert.equal(sd.steps.flushed, true);
    assert.equal(sd.steps.finalEvent, true);
    assert.equal(sd.steps.finalSnapshot, true);
    assert.equal(sd.steps.lockReleased, true);
    assert.ok(sd.steps.finalSnapshotId > 0);
    A._finalSnapshotId = sd.steps.finalSnapshotId; // stash for the redeploy block

    const { rows: flushed } = await pool.query(
      `SELECT COUNT(*) AS n FROM memory_events WHERE event_type = 'TRADE_OPENED' AND symbol = 'MI_FLUSH'`
    );
    assert.equal(Number(flushed[0].n), 1, "in-flight write flushed before exit");

    const { rows: ev } = await pool.query(
      `SELECT COUNT(*) AS n FROM memory_events WHERE dedupe_key = $1`,
      [`system_shutdown:${A.getStatus().bootId}`]
    );
    assert.equal(Number(ev[0].n), 1, "SYSTEM_SHUTDOWN event written once");
  });

  it("restart + redeploy simulation: next boot recovers from the shutdown snapshot, over the corrupt one", async () => {
    const B = new LiveMemoryIntegration({ calledBy: "test_mi_b" });
    const ini = await B.init();
    assert.equal(ini.ok, true);
    const rep = await B.recoverOnStartup({ liveState: { dailyTrades: 0, openTrades: {} } });
    assert.equal(rep.recovered, true, rep.reason);
    assert.equal(rep.lockAcquired, true, "lock was released by previous boot");
    // newest snapshot is the planted corrupt one → walk-back must land on A's shutdown snapshot
    assert.equal(rep.snapshotId, A._finalSnapshotId,
      `expected shutdown snapshot ${A._finalSnapshotId}, got ${rep.snapshotId}`);
    assert.ok(rep.snapshotsSkipped >= 1, "corrupt snapshot was walked over");
    // this boot wrote its own recovery event
    const { rows } = await pool.query(
      `SELECT COUNT(*) AS n FROM memory_events WHERE dedupe_key = $1`,
      [`system_recovery:${rep.bootId}`]
    );
    assert.equal(Number(rows[0].n), 1);
    await B.gracefulShutdown({ reason: "redeploy-test-done" });
  });
});
