-- ============================================================
-- SHADOW OS v2 — Migration 004: Memory Foundation
-- Sprint 3: MemoryManager
--
-- Purpose:
--   Creates memory_events — the central persistent event-memory
--   table of SHADOW OS. Every important event generated by any
--   component eventually becomes a Memory Entry here.
--
--   Creates memory_event_history — append-only audit trail of
--   every change to a memory event.
--
--   memory_entries (Migration 001) is intentionally UNTOUCHED.
--   It remains the namespace/key/value TTL cache described in
--   MASTER_ARCHITECTURE §6.2. One table cannot serve both the
--   TTL-cache contract (rows expire and are GC'd) and the
--   append-first memory contract (history never deleted), so
--   the rich event-memory model lives in its own table.
--
-- Sacred constraint:
--   No row may be deleted. No history may be modified.
--   All DDL uses IF NOT EXISTS — idempotent, safe to run
--   multiple times. Purely additive: no existing table,
--   column, or row is altered.
-- ============================================================

-- ── Step 1: memory_events ─────────────────────────────────────────────────
-- The central persistent memory of SHADOW OS.
-- Append-first: payload, event_type, and occurred_at are immutable
-- after creation (enforced in MemoryManager, not by triggers, to
-- keep the FROZEN production chain unaffected).

CREATE TABLE IF NOT EXISTS memory_events (
  id               BIGSERIAL        PRIMARY KEY,
  event_type       TEXT             NOT NULL,
  runtime_domain   TEXT             NOT NULL DEFAULT 'live',
  trade_intent_id  BIGINT,                          -- soft reference to trade_intents(id); validated by validateMemory()
  strategy_id      TEXT             NOT NULL DEFAULT 'default',
  symbol           TEXT,
  occurred_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),   -- when the remembered event happened (immutable)
  created_at       TIMESTAMPTZ      NOT NULL DEFAULT NOW(),   -- when the memory row was written
  updated_at       TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  importance       DOUBLE PRECISION NOT NULL DEFAULT 0.5,     -- 0.0 .. 1.0
  tags             TEXT[]           NOT NULL DEFAULT '{}',
  reasoning        TEXT,
  context          JSONB            NOT NULL DEFAULT '[]',    -- append-only array of addenda (appendMemory)
  payload          JSONB            NOT NULL DEFAULT '{}',    -- immutable event data
  source           TEXT             NOT NULL DEFAULT 'system',
  version          BIGINT           NOT NULL DEFAULT 1,
  status           TEXT             NOT NULL DEFAULT 'ACTIVE'
                   CHECK (status IN ('ACTIVE', 'ARCHIVED', 'CORRUPTED')),
  metadata         JSONB            NOT NULL DEFAULT '{}',
  dedupe_key       TEXT,                            -- optional idempotency key (no-duplicate-memories gate)
  CHECK (importance >= 0.0 AND importance <= 1.0)
);

-- Idempotency: at most one memory per dedupe_key (when provided).
CREATE UNIQUE INDEX IF NOT EXISTS idx_me_dedupe
  ON memory_events (dedupe_key) WHERE dedupe_key IS NOT NULL;

-- Query-path indexes (queryByDomain / queryByTrade / queryByTime /
-- queryByStrategy / searchMemory).
CREATE INDEX IF NOT EXISTS idx_me_event_type      ON memory_events (event_type);
CREATE INDEX IF NOT EXISTS idx_me_runtime_domain  ON memory_events (runtime_domain);
CREATE INDEX IF NOT EXISTS idx_me_trade_intent    ON memory_events (trade_intent_id) WHERE trade_intent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_me_strategy        ON memory_events (strategy_id);
CREATE INDEX IF NOT EXISTS idx_me_symbol          ON memory_events (symbol) WHERE symbol IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_me_occurred_at     ON memory_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_me_status          ON memory_events (status);
CREATE INDEX IF NOT EXISTS idx_me_importance      ON memory_events (importance DESC);
CREATE INDEX IF NOT EXISTS idx_me_tags            ON memory_events USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_me_status_domain   ON memory_events (status, runtime_domain);

-- ── Step 2: memory_event_history ──────────────────────────────────────────
-- Append-only audit trail. Full-row snapshot on every change.
-- SACRED: no row in this table may ever be deleted.

CREATE TABLE IF NOT EXISTS memory_event_history (
  id          BIGSERIAL   PRIMARY KEY,
  memory_id   BIGINT      NOT NULL REFERENCES memory_events(id),
  change_op   TEXT        NOT NULL
              CHECK (change_op IN ('CREATE','APPEND','UPDATE','TAG','ARCHIVE','RESTORE','VALIDATE')),
  version     BIGINT      NOT NULL,
  snapshot    JSONB       NOT NULL,                 -- full row snapshot AFTER the change
  changed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  changed_by  TEXT        NOT NULL DEFAULT 'system',
  detail      JSONB       NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_meh_memory_id  ON memory_event_history (memory_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_meh_changed_at ON memory_event_history (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_meh_change_op  ON memory_event_history (change_op);
