"use strict";
/**
 * MemoryManager — SHADOW OS v2, Sprint 3: Memory Foundation
 *
 * The central persistent memory layer of SHADOW OS.
 * Every important event generated by any component eventually
 * becomes a Memory Entry managed by this class.
 *
 * Two storage surfaces (one manager):
 *
 *   1. memory_events (+ memory_event_history) — the rich, append-first
 *      event-memory model. History is NEVER deleted. This is the
 *      foundation of future learning (KnowledgeManager, Sprint 4).
 *
 *   2. memory_entries — the namespace/key/value TTL cache described in
 *      MASTER_ARCHITECTURE §6.2 (kvGet/kvSet/kvGetAll/kvGc). TTL rows
 *      expire and are GC'd by design — this surface is a cache, not
 *      sacred memory.
 *
 * Memory principles (Sprint 3 spec):
 *   • Memory is append-first — payload, event_type and occurred_at are
 *     immutable after creation. appendMemory() only adds context addenda.
 *   • History must never be deleted — every mutation writes a full-row
 *     snapshot into memory_event_history in the same transaction.
 *   • Memory must survive restart / redeploy / crash / power failure —
 *     everything lives in PostgreSQL; no state is held in-process.
 *
 * Status machine:
 *   ACTIVE   ⇄ ARCHIVED    (archiveMemory / restoreMemory)
 *   ACTIVE   → CORRUPTED   (validateMemory finding — row is never deleted)
 *   CORRUPTED → ACTIVE     (restoreMemory after manual repair)
 *
 * Every mutation is:
 *   • Atomic    (SELECT FOR UPDATE + UPDATE + history INSERT, one transaction)
 *   • Audited   (memory_event_history, append-only, full-row snapshot)
 *   • Versioned (monotonic version counter; version === history row count)
 *
 * CAS pool deadlock rule (from replit.md):
 *   Never call pool.connect() while already holding a client.
 *   All reads within a mutation use the already-held client.
 *
 * Usage:
 *   const { MemoryManager } = require('./managers/MemoryManager');
 *   const mm = new MemoryManager({ connectionString: process.env.DATABASE_URL });
 *   await mm.init();
 *   const { row } = await mm.createMemory({
 *     event_type: 'TRADE_EXECUTED', runtime_domain: 'live',
 *     symbol: 'EUR_USD', payload: { price: 1.0842 },
 *   });
 *   await mm.appendMemory(row.id, { note: 'exit filled' });
 *   await mm.archiveMemory(row.id, 'trade complete');
 *   await mm.shutdown();
 *
 * Optional RDM integration:
 *   const mm = new MemoryManager({ connectionString, rdm });
 *   // validateMemory() findings are logged via rdm.logConsistency() when
 *   // available, falling back to direct consistency_log INSERTs.
 *
 * Requirements:
 *   - Migrations 001–004 must have been applied
 *   - DATABASE_URL must point to PostgreSQL 9.6+
 */

const { Pool } = require("pg");

// ── Constants ─────────────────────────────────────────────────────────────────

const VALID_STATUSES  = new Set(["ACTIVE", "ARCHIVED", "CORRUPTED"]);
const VALID_CHANGE_OPS = new Set(["CREATE", "APPEND", "UPDATE", "TAG", "ARCHIVE", "RESTORE", "VALIDATE"]);

/** Fields updateMemory() may change. Everything else is immutable or system-managed. */
const MUTABLE_FIELDS = new Set(["importance", "tags", "reasoning", "metadata"]);

/** Fields that may NEVER change after createMemory(). */
const IMMUTABLE_FIELDS = new Set([
  "event_type", "payload", "occurred_at", "runtime_domain",
  "trade_intent_id", "strategy_id", "symbol", "source", "dedupe_key",
]);

const REQUIRED_TABLES = [
  "memory_events",
  "memory_event_history",
  "memory_entries",
  "consistency_log",
];

// ── MemoryManager ─────────────────────────────────────────────────────────────

class MemoryManager {
  /**
   * @param {object}  options
   * @param {string}  [options.connectionString]     PostgreSQL connection string
   * @param {object}  [options._pool]                Pre-created pg.Pool (for testing)
   * @param {number}  [options.maxConnections=5]     Pool max connections
   * @param {number}  [options.idleTimeout=30000]    Pool idle timeout ms
   * @param {number}  [options.connectTimeout=10000] Pool connect timeout ms
   * @param {string}  [options.calledBy='system']    Default changed_by for history
   * @param {object}  [options.rdm]                  RuntimeDomainManager instance (optional)
   */
  constructor(options = {}) {
    if (options._pool) {
      this._pool    = options._pool;
      this._ownPool = false;
    } else {
      const connStr = (options.connectionString != null ? options.connectionString : process.env.DATABASE_URL) || "";
      if (!connStr.startsWith("postgres://") && !connStr.startsWith("postgresql://")) {
        throw new Error(
          `MemoryManager: connectionString must start with postgres:// or postgresql://. ` +
          `Got: "${connStr.slice(0, 20)}..."`
        );
      }
      this._pool = new Pool({
        connectionString:        connStr,
        max:                     options.maxConnections  ?? 5,
        idleTimeoutMillis:       options.idleTimeout     ?? 30000,
        connectionTimeoutMillis: options.connectTimeout  ?? 10000,
      });
      this._ownPool = true;
    }

    this._defaultCalledBy = options.calledBy || "system";
    this._rdm             = options.rdm       || null;
    this._ready           = false;
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  /**
   * Verifies all required tables exist. Must be called before any other method.
   * @returns {{ ok: boolean, tables: string[] }}
   */
  async init() {
    const client = await this._pool.connect();
    try {
      const { rows } = await client.query(
        `SELECT table_name
         FROM   information_schema.tables
         WHERE  table_schema = 'public'`
      );
      const found   = new Set(rows.map(r => r.table_name));
      const missing = REQUIRED_TABLES.filter(t => !found.has(t));
      if (missing.length > 0) {
        throw new Error(
          `MemoryManager.init(): missing required tables: ${missing.join(", ")}. ` +
          `Run migration 004 first.`
        );
      }
      this._ready = true;
      return { ok: true, tables: REQUIRED_TABLES };
    } finally {
      client.release();
    }
  }

  /** Shuts down the pool (only if owned by this instance). */
  async shutdown() {
    if (this._ownPool) await this._pool.end();
    this._ready = false;
  }

  /** Connectivity check. Safe to call before init(). */
  async ping() {
    const start = Date.now();
    await this._pool.query("SELECT 1");
    return { ok: true, latencyMs: Date.now() - start };
  }

  // ── Internal helpers ──────────────────────────────────────────────────────

  _assertReady() {
    if (!this._ready) {
      throw new Error("MemoryManager: call init() before using this manager.");
    }
  }

  _assertMemoryId(memoryId) {
    const n = Number(memoryId);
    if (!Number.isFinite(n) || n <= 0) {
      throw new Error(`MemoryManager: invalid memoryId: ${memoryId}`);
    }
    return n;
  }

  _assertImportance(importance) {
    const n = Number(importance);
    if (!Number.isFinite(n) || n < 0 || n > 1) {
      throw new Error(`MemoryManager: importance must be between 0.0 and 1.0, got: ${importance}`);
    }
    return n;
  }

  _assertTags(tags) {
    if (!Array.isArray(tags) || tags.some(t => typeof t !== "string" || !t.trim())) {
      throw new Error("MemoryManager: tags must be an array of non-empty strings");
    }
    return tags.map(t => t.trim());
  }

  /**
   * Writes the append-only audit record. SACRED: never deleted.
   * Must run on the caller's client inside the caller's transaction.
   */
  async _writeHistory(client, memoryId, changeOp, version, snapshotRow, changedBy, detail = {}) {
    if (!VALID_CHANGE_OPS.has(changeOp)) {
      throw new Error(`MemoryManager: invalid change_op '${changeOp}'`);
    }
    await client.query(
      `INSERT INTO memory_event_history
         (memory_id, change_op, version, snapshot, changed_by, detail)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [memoryId, changeOp, Number(version), JSON.stringify(snapshotRow), changedBy, JSON.stringify(detail)]
    );
  }

  /**
   * Core mutation engine.
   *
   * Locks the row (SELECT FOR UPDATE), verifies its current status is in
   * validFrom, applies the SET clause, bumps version, and writes the
   * full-row history snapshot — all in one transaction.
   *
   * @param {number}   memoryId
   * @param {string[]} validFrom   acceptable current status(es)
   * @param {string}   changeOp    CREATE/APPEND/UPDATE/TAG/ARCHIVE/RESTORE/VALIDATE
   * @param {string}   setClause   SQL SET fragment using $3..$N (row id is $1; $2 unused here)
   * @param {any[]}    setParams   parameters for the SET fragment
   * @param {string}   changedBy
   * @param {object}   detail
   * @param {string}   [toStatus]  when provided, status is also updated
   * @returns {object} updated row
   */
  async _mutate(memoryId, validFrom, changeOp, setFields, changedBy, detail = {}, toStatus = null) {
    const id = this._assertMemoryId(memoryId);
    const client = await this._pool.connect();
    try {
      await client.query("BEGIN");

      const { rows: lockRows } = await client.query(
        `SELECT id, status, version FROM memory_events WHERE id = $1 FOR UPDATE`,
        [id]
      );
      if (lockRows.length === 0) {
        throw new Error(`MemoryManager: memory ${id} not found`);
      }
      const current = lockRows[0];
      if (!validFrom.includes(current.status)) {
        throw new Error(
          `MemoryManager: invalid ${changeOp} on memory ${id}: ` +
          `status is '${current.status}' (expected one of: ${validFrom.join(", ")})`
        );
      }

      // Build SET clause: $1 = id, extra params from $2
      const keys = Object.keys(setFields);
      const vals = Object.values(setFields);
      const sets = keys.map((k, i) => `${k} = $${i + 2}`);
      if (toStatus) {
        sets.push(`status = $${keys.length + 2}`);
        vals.push(toStatus);
      }
      sets.push(`version = version + 1`, `updated_at = NOW()`);

      const { rows } = await client.query(
        `UPDATE memory_events SET ${sets.join(", ")} WHERE id = $1 RETURNING *`,
        [id, ...vals]
      );
      const row = rows[0];

      await this._writeHistory(client, id, changeOp, Number(row.version), row, changedBy, {
        from_status: current.status,
        to_status:   row.status,
        ...detail,
      });

      await client.query("COMMIT");
      return row;
    } catch (err) {
      await client.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      client.release();
    }
  }

  /** Logs to consistency_log — via RDM when available, direct INSERT otherwise. */
  async _logConsistency(checkId, severity, description, detail = null) {
    if (this._rdm && typeof this._rdm.logConsistency === "function") {
      try {
        return await this._rdm.logConsistency(checkId, severity, description, detail);
      } catch (_) {
        // fall through to direct insert
      }
    }
    const { rows } = await this._pool.query(
      `INSERT INTO consistency_log (check_id, severity, description, detail)
       VALUES ($1, $2, $3, $4) RETURNING id, detected_at`,
      [checkId, severity, description, detail ? JSON.stringify(detail) : null]
    );
    return { id: rows[0].id, detectedAt: rows[0].detected_at };
  }

  // ── Write API (memory_events) ─────────────────────────────────────────────

  /**
   * Creates a new Memory Entry (version=1, status=ACTIVE).
   *
   * Idempotent on dedupe_key: when data.dedupe_key is provided and a memory
   * with that key already exists, returns
   * { created: false, duplicate: true, row: existingRow }.
   *
   * @param {object}  data
   * @param {string}   data.event_type                Required. e.g. TRADE_EXECUTED
   * @param {string}  [data.runtime_domain='live']
   * @param {number}  [data.trade_intent_id]          Soft reference to trade_intents.id
   * @param {string}  [data.strategy_id='default']
   * @param {string}  [data.symbol]
   * @param {Date|string} [data.occurred_at]          When the event happened (immutable)
   * @param {number}  [data.importance=0.5]           0.0 – 1.0
   * @param {string[]}[data.tags=[]]
   * @param {string}  [data.reasoning]
   * @param {object}  [data.payload={}]               Immutable event data
   * @param {string}  [data.source='system']
   * @param {object}  [data.metadata={}]
   * @param {string}  [data.dedupe_key]               Optional idempotency key
   * @param {object}  [opts]
   * @param {string}  [opts.calledBy]
   * @returns {{ created: boolean, duplicate: boolean, row: object }}
   */
  async createMemory(data = {}, opts = {}) {
    this._assertReady();

    if (!data.event_type || typeof data.event_type !== "string" || !data.event_type.trim()) {
      throw new Error("MemoryManager.createMemory: event_type is required");
    }
    const importance = data.importance != null ? this._assertImportance(data.importance) : 0.5;
    const tags       = data.tags != null ? this._assertTags(data.tags) : [];
    if (data.payload != null && (typeof data.payload !== "object" || Array.isArray(data.payload))) {
      throw new Error("MemoryManager.createMemory: payload must be a plain object");
    }
    if (data.metadata != null && (typeof data.metadata !== "object" || Array.isArray(data.metadata))) {
      throw new Error("MemoryManager.createMemory: metadata must be a plain object");
    }
    if (data.trade_intent_id != null && (!Number.isFinite(Number(data.trade_intent_id)) || Number(data.trade_intent_id) <= 0)) {
      throw new Error("MemoryManager.createMemory: trade_intent_id must be a positive number");
    }
    if (data.dedupe_key != null && (typeof data.dedupe_key !== "string" || !data.dedupe_key.trim())) {
      throw new Error("MemoryManager.createMemory: dedupe_key must be a non-empty string");
    }

    const changedBy = opts.calledBy || this._defaultCalledBy;
    const client = await this._pool.connect();
    try {
      await client.query("BEGIN");

      const { rows } = await client.query(
        `INSERT INTO memory_events
           (event_type, runtime_domain, trade_intent_id, strategy_id, symbol,
            occurred_at, importance, tags, reasoning, payload, source, metadata, dedupe_key)
         VALUES ($1, $2, $3, $4, $5, COALESCE($6, NOW()), $7, $8, $9, $10, $11, $12, $13)
         ON CONFLICT (dedupe_key) WHERE dedupe_key IS NOT NULL DO NOTHING
         RETURNING *`,
        [
          data.event_type.trim(),
          data.runtime_domain || "live",
          data.trade_intent_id != null ? Number(data.trade_intent_id) : null,
          data.strategy_id || "default",
          data.symbol || null,
          data.occurred_at || null,
          importance,
          tags,
          data.reasoning || null,
          JSON.stringify(data.payload || {}),
          data.source || "system",
          JSON.stringify(data.metadata || {}),
          data.dedupe_key ? data.dedupe_key.trim() : null,
        ]
      );

      if (rows.length === 0) {
        // dedupe_key conflict — return the existing memory (no history write).
        // IMPORTANT: reuse the already-held client. Calling this._pool.query()
        // here would acquire a SECOND connection while this one is still held,
        // deadlocking the pool under concurrent load (pool.max callers each
        // holding one client and waiting for another).
        await client.query("ROLLBACK");
        const { rows: existing } = await client.query(
          `SELECT * FROM memory_events WHERE dedupe_key = $1`,
          [data.dedupe_key.trim()]
        );
        return { created: false, duplicate: true, row: existing[0] || null };
      }

      const row = rows[0];
      await this._writeHistory(client, row.id, "CREATE", 1, row, changedBy, { event_type: row.event_type });
      await client.query("COMMIT");
      return { created: true, duplicate: false, row };
    } catch (err) {
      await client.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      client.release();
    }
  }

  /**
   * Appends an addendum to a memory's context array.
   * The ONLY way to add information to an existing memory — payload,
   * event_type, and occurred_at are immutable forever.
   *
   * @param {number} memoryId
   * @param {object} addendum        Any JSON-serializable object
   * @param {object} [opts]
   * @param {string} [opts.calledBy]
   * @returns {{ row: object }}
   */
  async appendMemory(memoryId, addendum, opts = {}) {
    this._assertReady();
    if (addendum == null || typeof addendum !== "object" || Array.isArray(addendum)) {
      throw new Error("MemoryManager.appendMemory: addendum must be a plain object");
    }
    const id        = this._assertMemoryId(memoryId);
    const changedBy = opts.calledBy || this._defaultCalledBy;
    const entry = {
      appended_at: new Date().toISOString(),
      appended_by: changedBy,
      addendum,
    };

    const client = await this._pool.connect();
    try {
      await client.query("BEGIN");
      const { rows: lockRows } = await client.query(
        `SELECT id, status, version FROM memory_events WHERE id = $1 FOR UPDATE`,
        [id]
      );
      if (lockRows.length === 0) throw new Error(`MemoryManager: memory ${id} not found`);
      const current = lockRows[0];
      if (current.status !== "ACTIVE") {
        throw new Error(
          `MemoryManager: invalid APPEND on memory ${id}: status is '${current.status}' (expected one of: ACTIVE)`
        );
      }

      // JSONB array concatenation — context only ever grows
      const { rows } = await client.query(
        `UPDATE memory_events
         SET context = context || $2::jsonb, version = version + 1, updated_at = NOW()
         WHERE id = $1 RETURNING *`,
        [id, JSON.stringify([entry])]
      );
      const row = rows[0];
      await this._writeHistory(client, id, "APPEND", Number(row.version), row, changedBy, {
        addendum_keys: Object.keys(addendum),
      });
      await client.query("COMMIT");
      return { row };
    } catch (err) {
      await client.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      client.release();
    }
  }

  /**
   * Updates mutable fields only: importance, tags, reasoning, metadata.
   * Attempts to change immutable fields (payload, event_type, occurred_at, …)
   * throw immediately — append-first is sacred.
   *
   * @param {number} memoryId
   * @param {object} patch          { importance?, tags?, reasoning?, metadata? }
   * @param {object} [opts]
   * @returns {{ row: object }}
   */
  async updateMemory(memoryId, patch = {}, opts = {}) {
    this._assertReady();
    const keys = Object.keys(patch);
    if (keys.length === 0) {
      throw new Error("MemoryManager.updateMemory: patch must contain at least one field");
    }
    for (const k of keys) {
      if (IMMUTABLE_FIELDS.has(k)) {
        throw new Error(
          `MemoryManager.updateMemory: '${k}' is immutable — memory is append-first. ` +
          `Use appendMemory() to add context.`
        );
      }
      if (!MUTABLE_FIELDS.has(k)) {
        throw new Error(`MemoryManager.updateMemory: unknown or non-mutable field '${k}'`);
      }
    }

    const setFields = {};
    if (patch.importance != null) setFields.importance = this._assertImportance(patch.importance);
    if (patch.tags != null)       setFields.tags       = this._assertTags(patch.tags);
    if (patch.reasoning !== undefined) {
      if (patch.reasoning !== null && typeof patch.reasoning !== "string") {
        throw new Error("MemoryManager.updateMemory: reasoning must be a string or null");
      }
      setFields.reasoning = patch.reasoning;
    }
    if (patch.metadata != null) {
      if (typeof patch.metadata !== "object" || Array.isArray(patch.metadata)) {
        throw new Error("MemoryManager.updateMemory: metadata must be a plain object");
      }
      setFields.metadata = JSON.stringify(patch.metadata);
    }

    const changedBy = opts.calledBy || this._defaultCalledBy;
    const row = await this._mutate(
      memoryId, ["ACTIVE"], "UPDATE", setFields, changedBy, { patched: keys }
    );
    return { row };
  }

  /**
   * Adds and/or removes tags. Convenience wrapper with TAG audit op.
   *
   * @param {number}   memoryId
   * @param {object}   change          { add?: string[], remove?: string[] }
   * @param {object}   [opts]
   * @returns {{ row: object }}
   */
  async tagMemory(memoryId, change = {}, opts = {}) {
    this._assertReady();
    const add    = change.add    != null ? this._assertTags(change.add)    : [];
    const remove = change.remove != null ? this._assertTags(change.remove) : [];
    if (add.length === 0 && remove.length === 0) {
      throw new Error("MemoryManager.tagMemory: provide tags to add and/or remove");
    }

    const id = this._assertMemoryId(memoryId);
    const changedBy = opts.calledBy || this._defaultCalledBy;

    const client = await this._pool.connect();
    try {
      await client.query("BEGIN");
      const { rows: lockRows } = await client.query(
        `SELECT id, status, version, tags FROM memory_events WHERE id = $1 FOR UPDATE`,
        [id]
      );
      if (lockRows.length === 0) throw new Error(`MemoryManager: memory ${id} not found`);
      const current = lockRows[0];
      if (current.status !== "ACTIVE") {
        throw new Error(
          `MemoryManager: invalid TAG on memory ${id}: status is '${current.status}' (expected one of: ACTIVE)`
        );
      }

      const next = Array.from(new Set(
        current.tags.filter(t => !remove.includes(t)).concat(add)
      ));

      const { rows } = await client.query(
        `UPDATE memory_events
         SET tags = $2, version = version + 1, updated_at = NOW()
         WHERE id = $1 RETURNING *`,
        [id, next]
      );
      const row = rows[0];
      await this._writeHistory(client, id, "TAG", Number(row.version), row, changedBy, { added: add, removed: remove });
      await client.query("COMMIT");
      return { row };
    } catch (err) {
      await client.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      client.release();
    }
  }

  /**
   * ACTIVE → ARCHIVED. The memory remains fully readable and restorable.
   * Nothing is ever deleted.
   *
   * @param {number} memoryId
   * @param {string} [reason]
   * @param {object} [opts]
   * @returns {{ row: object }}
   */
  async archiveMemory(memoryId, reason = null, opts = {}) {
    this._assertReady();
    const changedBy = opts.calledBy || this._defaultCalledBy;
    const row = await this._mutate(
      memoryId, ["ACTIVE"], "ARCHIVE", {}, changedBy, { reason }, "ARCHIVED"
    );
    return { row };
  }

  /**
   * ARCHIVED → ACTIVE, or CORRUPTED → ACTIVE (after manual repair).
   *
   * @param {number} memoryId
   * @param {string} [reason]
   * @param {object} [opts]
   * @returns {{ row: object }}
   */
  async restoreMemory(memoryId, reason = null, opts = {}) {
    this._assertReady();
    const changedBy = opts.calledBy || this._defaultCalledBy;
    const row = await this._mutate(
      memoryId, ["ARCHIVED", "CORRUPTED"], "RESTORE", {}, changedBy, { reason }, "ACTIVE"
    );
    return { row };
  }

  // ── Read / Query API ──────────────────────────────────────────────────────

  /** Returns a memory by id, or null. */
  async getMemory(memoryId) {
    this._assertReady();
    const id = this._assertMemoryId(memoryId);
    const { rows } = await this._pool.query(
      `SELECT * FROM memory_events WHERE id = $1`, [id]
    );
    return rows[0] || null;
  }

  /** Full append-only audit trail for one memory (most recent first). */
  async getMemoryHistory(memoryId, opts = {}) {
    this._assertReady();
    const id = this._assertMemoryId(memoryId);
    const limit = Math.min(Number(opts.limit) || 100, 1000);
    const { rows } = await this._pool.query(
      `SELECT id, memory_id, change_op, version, snapshot, changed_at, changed_by, detail
       FROM memory_event_history
       WHERE memory_id = $1
       ORDER BY changed_at DESC, id DESC
       LIMIT $2`,
      [id, limit]
    );
    return rows;
  }

  /**
   * General-purpose search across memory_events.
   *
   * @param {object}  [filters]
   * @param {string}   [filters.event_type]
   * @param {string}   [filters.runtime_domain]
   * @param {string}   [filters.strategy_id]
   * @param {string}   [filters.symbol]
   * @param {string}   [filters.source]
   * @param {string}   [filters.status='ACTIVE']    Or 'ANY' for all statuses
   * @param {string[]} [filters.tagsAny]            Rows with at least one of these tags
   * @param {string[]} [filters.tagsAll]            Rows with all of these tags
   * @param {number}   [filters.minImportance]
   * @param {string}   [filters.text]               ILIKE match on reasoning
   * @param {Date|string} [filters.since]           occurred_at >= since
   * @param {Date|string} [filters.until]           occurred_at <= until
   * @param {number}   [filters.trade_intent_id]
   * @param {number}   [filters.limit=100]          Max 1000
   * @param {number}   [filters.offset=0]
   * @param {string}   [filters.order='occurred_at DESC']  or 'importance DESC'
   * @returns {object[]}
   */
  async searchMemory(filters = {}) {
    this._assertReady();
    const where  = [];
    const params = [];
    let   p      = 0;

    const eq = (col, val) => { params.push(val); where.push(`${col} = $${++p}`); };

    if (filters.event_type)      eq("event_type", filters.event_type);
    if (filters.runtime_domain)  eq("runtime_domain", filters.runtime_domain);
    if (filters.strategy_id)     eq("strategy_id", filters.strategy_id);
    if (filters.symbol)          eq("symbol", filters.symbol);
    if (filters.source)          eq("source", filters.source);
    if (filters.trade_intent_id) eq("trade_intent_id", Number(filters.trade_intent_id));

    const status = filters.status || "ACTIVE";
    if (status !== "ANY") {
      if (!VALID_STATUSES.has(status)) {
        throw new Error(`MemoryManager.searchMemory: invalid status '${status}'`);
      }
      eq("status", status);
    }

    // GIN operators — NEVER use ANY($1) with a JS array (documented pg bug)
    if (filters.tagsAny) {
      params.push(this._assertTags(filters.tagsAny));
      where.push(`tags && $${++p}::text[]`);
    }
    if (filters.tagsAll) {
      params.push(this._assertTags(filters.tagsAll));
      where.push(`tags @> $${++p}::text[]`);
    }
    if (filters.minImportance != null) {
      params.push(this._assertImportance(filters.minImportance));
      where.push(`importance >= $${++p}`);
    }
    if (filters.text) {
      params.push(`%${filters.text}%`);
      where.push(`reasoning ILIKE $${++p}`);
    }
    if (filters.since) { params.push(filters.since); where.push(`occurred_at >= $${++p}`); }
    if (filters.until) { params.push(filters.until); where.push(`occurred_at <= $${++p}`); }

    const order = filters.order === "importance DESC"
      ? "importance DESC, occurred_at DESC"
      : "occurred_at DESC, id DESC";
    const limit  = Math.min(Number(filters.limit) || 100, 1000);
    const offset = Math.max(Number(filters.offset) || 0, 0);
    params.push(limit, offset);

    const sql = `
      SELECT * FROM memory_events
      ${where.length ? "WHERE " + where.join(" AND ") : ""}
      ORDER BY ${order}
      LIMIT $${++p} OFFSET $${++p}`;

    const { rows } = await this._pool.query(sql, params);
    return rows;
  }

  /** Memories for one runtime domain. */
  async queryByDomain(runtimeDomain, opts = {}) {
    if (!runtimeDomain || typeof runtimeDomain !== "string") {
      throw new Error("MemoryManager.queryByDomain: runtimeDomain is required");
    }
    return this.searchMemory({ ...opts, runtime_domain: runtimeDomain });
  }

  /** Memories linked to one trade intent. */
  async queryByTrade(tradeIntentId, opts = {}) {
    const n = Number(tradeIntentId);
    if (!Number.isFinite(n) || n <= 0) {
      throw new Error("MemoryManager.queryByTrade: tradeIntentId must be a positive number");
    }
    return this.searchMemory({ ...opts, trade_intent_id: n });
  }

  /** Memories in a time window (occurred_at). */
  async queryByTime(since, until, opts = {}) {
    if (!since && !until) {
      throw new Error("MemoryManager.queryByTime: provide since and/or until");
    }
    return this.searchMemory({ ...opts, since, until });
  }

  /** Memories for one strategy. */
  async queryByStrategy(strategyId, opts = {}) {
    if (!strategyId || typeof strategyId !== "string") {
      throw new Error("MemoryManager.queryByStrategy: strategyId is required");
    }
    return this.searchMemory({ ...opts, strategy_id: strategyId });
  }

  // ── Summarization & Validation ────────────────────────────────────────────

  /**
   * Pure-SQL aggregation over memory_events. The output shape feeds
   * system_snapshots.memory_summary.
   *
   * @param {object} [opts]
   * @param {Date|string} [opts.since]   Restrict to occurred_at >= since
   * @returns {{ total, byStatus, byEventType, byDomain, byStrategy, bySymbol,
   *             importance: { avg, min, max }, timeRange: { oldest, newest },
   *             topTags, historyRows, generatedAt }}
   */
  async summarizeMemory(opts = {}) {
    this._assertReady();
    const params = [];
    let timeFilter = "";
    if (opts.since) {
      params.push(opts.since);
      timeFilter = "WHERE occurred_at >= $1";
    }

    const [totals, byType, byDomain, byStrategy, bySymbol, byStatus, imp, range, tags, hist] =
      await Promise.all([
        this._pool.query(`SELECT COUNT(*) AS n FROM memory_events ${timeFilter}`, params),
        this._pool.query(`SELECT event_type, COUNT(*) AS n FROM memory_events ${timeFilter} GROUP BY event_type ORDER BY n DESC`, params),
        this._pool.query(`SELECT runtime_domain, COUNT(*) AS n FROM memory_events ${timeFilter} GROUP BY runtime_domain ORDER BY n DESC`, params),
        this._pool.query(`SELECT strategy_id, COUNT(*) AS n FROM memory_events ${timeFilter} GROUP BY strategy_id ORDER BY n DESC`, params),
        this._pool.query(`SELECT symbol, COUNT(*) AS n FROM memory_events ${timeFilter ? timeFilter + " AND" : "WHERE"} symbol IS NOT NULL GROUP BY symbol ORDER BY n DESC`, params),
        this._pool.query(`SELECT status, COUNT(*) AS n FROM memory_events ${timeFilter} GROUP BY status`, params),
        this._pool.query(`SELECT AVG(importance) AS avg, MIN(importance) AS min, MAX(importance) AS max FROM memory_events ${timeFilter}`, params),
        this._pool.query(`SELECT MIN(occurred_at) AS oldest, MAX(occurred_at) AS newest FROM memory_events ${timeFilter}`, params),
        this._pool.query(
          `SELECT tag, COUNT(*) AS n
           FROM memory_events, LATERAL unnest(tags) AS tag
           ${timeFilter}
           GROUP BY tag ORDER BY n DESC LIMIT 20`,
          params
        ),
        this._pool.query(`SELECT COUNT(*) AS n FROM memory_event_history`),
      ]);

    const toMap = (rows, keyCol) =>
      Object.fromEntries(rows.map(r => [r[keyCol] ?? "null", Number(r.n)]));

    return {
      total:       Number(totals.rows[0].n),
      byStatus:    toMap(byStatus.rows, "status"),
      byEventType: toMap(byType.rows, "event_type"),
      byDomain:    toMap(byDomain.rows, "runtime_domain"),
      byStrategy:  toMap(byStrategy.rows, "strategy_id"),
      bySymbol:    toMap(bySymbol.rows, "symbol"),
      importance: {
        avg: imp.rows[0].avg != null ? Number(imp.rows[0].avg) : null,
        min: imp.rows[0].min != null ? Number(imp.rows[0].min) : null,
        max: imp.rows[0].max != null ? Number(imp.rows[0].max) : null,
      },
      timeRange: {
        oldest: range.rows[0].oldest,
        newest: range.rows[0].newest,
      },
      topTags:     toMap(tags.rows, "tag"),
      historyRows: Number(hist.rows[0].n),
      generatedAt: new Date().toISOString(),
    };
  }

  /**
   * Structural integrity validation. Never deletes anything.
   *
   * Checks:
   *   1. context must be a JSON array
   *   2. payload must be a JSON object
   *   3. metadata must be a JSON object
   *   4. event_type must be non-empty
   *   5. orphaned trade_intent_id (soft-reference check)      → WARN finding
   *   6. version vs history-row-count continuity              → WARN finding
   *
   * Structural failures (1–4) mark the row CORRUPTED (VALIDATE op, audited).
   * All findings are logged to consistency_log.
   *
   * @param {object} [opts]
   * @param {boolean} [opts.markCorrupted=true]
   * @returns {{ checked, issues: object[], corrupted: number[], ok: boolean }}
   */
  async validateMemory(opts = {}) {
    this._assertReady();
    const markCorrupted = opts.markCorrupted !== false;
    const changedBy     = opts.calledBy || this._defaultCalledBy;
    const issues = [];

    const { rows: totalRows } = await this._pool.query(`SELECT COUNT(*) AS n FROM memory_events`);
    const checked = Number(totalRows[0].n);

    // 1–4: structural checks (single scan)
    const { rows: structural } = await this._pool.query(`
      SELECT id,
             jsonb_typeof(context)  AS context_type,
             jsonb_typeof(payload)  AS payload_type,
             jsonb_typeof(metadata) AS metadata_type,
             event_type, status
      FROM memory_events
      WHERE jsonb_typeof(context)  <> 'array'
         OR jsonb_typeof(payload)  <> 'object'
         OR jsonb_typeof(metadata) <> 'object'
         OR btrim(event_type) = ''
    `);

    for (const r of structural) {
      const problems = [];
      if (r.context_type  !== "array")  problems.push(`context is ${r.context_type} (expected array)`);
      if (r.payload_type  !== "object") problems.push(`payload is ${r.payload_type} (expected object)`);
      if (r.metadata_type !== "object") problems.push(`metadata is ${r.metadata_type} (expected object)`);
      if (!r.event_type || !r.event_type.trim()) problems.push("event_type is empty");
      issues.push({ memoryId: Number(r.id), check: "structural", severity: "ERROR", detail: problems.join("; ") });
    }

    // 5: orphaned trade_intent_id — LEFT JOIN, never ANY($1) (documented pg bug)
    const { rows: orphans } = await this._pool.query(`
      SELECT m.id, m.trade_intent_id
      FROM memory_events m
      LEFT JOIN trade_intents t ON t.id = m.trade_intent_id
      WHERE m.trade_intent_id IS NOT NULL AND t.id IS NULL
    `);
    for (const r of orphans) {
      issues.push({
        memoryId: Number(r.id), check: "orphaned_trade_intent", severity: "WARN",
        detail: `trade_intent_id ${r.trade_intent_id} does not exist in trade_intents`,
      });
    }

    // 6: version vs history continuity
    const { rows: gaps } = await this._pool.query(`
      SELECT m.id, m.version, COUNT(h.id) AS history_count
      FROM memory_events m
      LEFT JOIN memory_event_history h ON h.memory_id = m.id
      GROUP BY m.id, m.version
      HAVING COUNT(h.id) <> m.version
    `);
    for (const r of gaps) {
      issues.push({
        memoryId: Number(r.id), check: "version_history_gap", severity: "WARN",
        detail: `version=${r.version} but history rows=${r.history_count}`,
      });
    }

    // Mark structurally broken rows CORRUPTED (audited; never deleted)
    const corrupted = [];
    if (markCorrupted) {
      for (const issue of issues) {
        if (issue.check !== "structural") continue;
        try {
          await this._mutate(
            issue.memoryId, ["ACTIVE", "ARCHIVED"], "VALIDATE", {}, changedBy,
            { finding: issue.detail }, "CORRUPTED"
          );
          corrupted.push(issue.memoryId);
        } catch (_) {
          // already CORRUPTED or concurrently mutated — finding is still logged
        }
      }
    }

    // Log all findings to consistency_log
    for (const issue of issues) {
      await this._logConsistency(
        `memory_validate:${issue.check}`,
        issue.severity === "ERROR" ? "ERROR" : "WARN",
        `MemoryManager.validateMemory: memory ${issue.memoryId}: ${issue.detail}`,
        issue
      );
    }

    return { checked, issues, corrupted, ok: issues.length === 0 };
  }

  // ── KV surface (memory_entries — TTL cache per MASTER_ARCHITECTURE §6.2) ──

  /**
   * Upserts a namespace/key/value cache entry.
   * @param {string} namespace
   * @param {string} key
   * @param {any}    value                 JSON-serializable
   * @param {object} [opts]
   * @param {number} [opts.ttlSeconds]     Omit for no expiry
   * @param {string[]} [opts.tags]
   * @returns {{ row: object }}
   */
  async kvSet(namespace, key, value, opts = {}) {
    this._assertReady();
    if (!namespace || typeof namespace !== "string") throw new Error("MemoryManager.kvSet: namespace required");
    if (!key || typeof key !== "string")             throw new Error("MemoryManager.kvSet: key required");
    const tags = opts.tags != null ? this._assertTags(opts.tags) : [];
    const ttl  = opts.ttlSeconds != null ? Number(opts.ttlSeconds) : null;
    if (ttl != null && (!Number.isFinite(ttl) || ttl <= 0)) {
      throw new Error("MemoryManager.kvSet: ttlSeconds must be a positive number");
    }
    const { rows } = await this._pool.query(
      `INSERT INTO memory_entries (namespace, key, value, tags, expires_at)
       VALUES ($1, $2, $3, $4, ${ttl != null ? `NOW() + ($5 || ' seconds')::interval` : "NULL"})
       ON CONFLICT (namespace, key) DO UPDATE
         SET value = EXCLUDED.value,
             tags = EXCLUDED.tags,
             expires_at = EXCLUDED.expires_at,
             updated_at = NOW()
       RETURNING *`,
      ttl != null
        ? [namespace, key, JSON.stringify(value), tags, String(ttl)]
        : [namespace, key, JSON.stringify(value), tags]
    );
    return { row: rows[0] };
  }

  /**
   * Returns the value for namespace/key, or null when missing or expired.
   * Never throws for expired entries. Increments access_count.
   */
  async kvGet(namespace, key) {
    this._assertReady();
    const { rows } = await this._pool.query(
      `UPDATE memory_entries
       SET access_count = access_count + 1
       WHERE namespace = $1 AND key = $2
         AND (expires_at IS NULL OR expires_at > NOW())
       RETURNING value`,
      [namespace, key]
    );
    return rows.length > 0 ? rows[0].value : null;
  }

  /** All non-expired entries in a namespace: { key: value }. */
  async kvGetAll(namespace) {
    this._assertReady();
    const { rows } = await this._pool.query(
      `SELECT key, value FROM memory_entries
       WHERE namespace = $1
         AND (expires_at IS NULL OR expires_at > NOW())
       ORDER BY key`,
      [namespace]
    );
    return Object.fromEntries(rows.map(r => [r.key, r.value]));
  }

  /**
   * Garbage-collects expired cache entries (memory_entries ONLY — the
   * event-memory tables are never touched). Logged to consistency_log.
   * @returns {{ removed: number }}
   */
  async kvGc() {
    this._assertReady();
    const { rowCount } = await this._pool.query(
      `DELETE FROM memory_entries WHERE expires_at IS NOT NULL AND expires_at < NOW()`
    );
    if (rowCount > 0) {
      await this._logConsistency(
        "memory_kv_gc", "INFO",
        `MemoryManager.kvGc: removed ${rowCount} expired cache entries`,
        { removed: rowCount }
      );
    }
    return { removed: rowCount };
  }

  // ── Health ────────────────────────────────────────────────────────────────

  /**
   * @returns {{ total, byStatus, historyRows, kvEntries, pool }}
   */
  async getStats() {
    this._assertReady();
    const [tot, byStatus, hist, kv] = await Promise.all([
      this._pool.query(`SELECT COUNT(*) AS n FROM memory_events`),
      this._pool.query(`SELECT status, COUNT(*) AS n FROM memory_events GROUP BY status`),
      this._pool.query(`SELECT COUNT(*) AS n FROM memory_event_history`),
      this._pool.query(`SELECT COUNT(*) AS n FROM memory_entries`),
    ]);
    return {
      total:       Number(tot.rows[0].n),
      byStatus:    Object.fromEntries(byStatus.rows.map(r => [r.status, Number(r.n)])),
      historyRows: Number(hist.rows[0].n),
      kvEntries:   Number(kv.rows[0].n),
      pool: {
        total:   this._pool.totalCount,
        idle:    this._pool.idleCount,
        waiting: this._pool.waitingCount,
      },
    };
  }
}

module.exports = { MemoryManager, VALID_STATUSES, VALID_CHANGE_OPS, MUTABLE_FIELDS, IMMUTABLE_FIELDS };
